### ISSUE TITLE
Webhook not triggering Flow

### ISSUE THREAD

**Issue by sossienl** [jordenc/webhook.manager#2]
I'm on 1.3.0 Rc7 and seems like for some reason my flow is not triggered. Unfortunately I have not used Webhook manager before to validate if it has to do with 1.3.x. 

My PHP code:
`
    $file = file_get_contents("https://webhooks.athom.com/webhook/***/?token=***&event=PersoonLocatie&data1=data_field_1_here&data2=data_field_2_here&data3=data_field_3_here");
    print_r($file);
    `

Results in "OK".

My Flow in Homey:
<img width="939" alt="screen shot 2017-05-17 at 15 17 31" src="https://cloud.githubusercontent.com/assets/609650/26155669/4571c2d0-3b14-11e7-8372-33566cc10609.png">

Nothing happens in Telegram.

**Comment by jordenc** [comment]
Can you try to have a "speech" confirmation of the incoming message, to see if it triggers correctly? The message could have troubles on the Telegram side.

I use this app daily on 1.3.0 RC7 and experience no troubles. Just tested it again.
